PUT http://localhost:5000/songs/songs-Zt1Z0UabRhRlw8pB
Content-Type: application/json

{
  "title": "EE revision 2",
  "year": 2020,
  "performer": "Dimas",
  "duration": 120,
  "genre": "Pop"
}

###
